apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: httpd-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: httpd-container
          image: akmaster/newhttpd
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
